# Generated by Django 2.1.5 on 2019-02-15 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartCommodityMid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cart_commodity_mid',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(default='0.jpg', upload_to='commodity/thumbnail')),
                ('description', models.CharField(max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField(default=0)),
                ('buy_quantity', models.IntegerField(default=0)),
                ('is_exist', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_pay', models.BooleanField(blank=True, default=False)),
                ('is_send', models.BooleanField(blank=True, default=False)),
                ('is_finish', models.BooleanField(blank=True, default=False)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('number', models.IntegerField(blank=True, default=0)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderCommodityMid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Commodity')),
            ],
            options={
                'db_table': 'order_commodity_mid',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_extension',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='commodities',
            field=models.ManyToManyField(related_name='order_commodities', to='administrator.OrderCommodityMid'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commodity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Type'),
        ),
        migrations.AddField(
            model_name='cartcommoditymid',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Commodity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='commodities',
            field=models.ManyToManyField(related_name='cart_commodities', to='administrator.CartCommodityMid'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
