# Generated by Django 2.1.5 on 2019-02-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190215_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='confirm_order_id',
            field=models.IntegerField(default=0),
        ),
    ]
