# Generated by Django 2.1.5 on 2019-02-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_userextension_confirm_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirm',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
