# Generated by Django 2.1.5 on 2019-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_order_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_quit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
