# Generated by Django 2.1.5 on 2019-02-16 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0006_auto_20190216_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
