# Generated by Django 2.1.5 on 2019-02-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0008_auto_20190216_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_key', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('is_read', models.BooleanField(blank=True, default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'read_message',
            },
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='new_message',
        ),
    ]
