# Generated by Django 2.1.5 on 2019-02-17 03:03

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20190217_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreadmessage',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
