# Generated by Django 2.1.5 on 2019-02-17 03:06

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20190217_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='create_time',
            new_name='creat_time',
        ),
        migrations.RemoveField(
            model_name='userreadmessage',
            name='create_time',
        ),
        migrations.AddField(
            model_name='userreadmessage',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
